"""empty message

Revision ID: 66759db647bd
Revises: 8a07f96bc311
Create Date: 2020-04-12 12:21:31.448131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66759db647bd'
down_revision = '8a07f96bc311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'date')
    # ### end Alembic commands ###
