"""empty message

Revision ID: ccdbd43c354b
Revises: 5ba9fc68a503
Create Date: 2020-04-10 23:50:02.459267

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Enum
from sqlalchemy.dialects import postgresql
# revision identifiers, used by Alembic.
revision = 'ccdbd43c354b'
down_revision = '5ba9fc68a503'
branch_labels = None
depends_on = None


def upgrade():
    dish_type = postgresql.ENUM('appetizers', 'salads', 'pasta & rissoto', 'seafood', 'from the grill', 'main dishes',
     'desserts', 'drink', name='dish_type')
    dish_type.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('dish_type', Enum('appetizers', 'salads', 'pasta & rissoto', 'seafood', 'from the grill', 'main dishes',
     'desserts', 'drink', name='dish_type'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dishes', 'dish_type')
    dish_type = postgresql.ENUM('appetizers', 'salads', 'pasta & rissoto', 'seafood', 'from the grill', 'main dishes',
     'desserts', 'drink', name='dish_type')
    dish_type.drop(op.get_bind())
    # ### end Alembic commands ###
